### ISSUE TITLE
Error when throwing an object to the ground from the equipment

### ISSUE THREAD

**Issue by frangaliano** [Suprcode/Crystal#879] opened 2023-12-09 14:45 UTC
Hi all,

When you throw an equipped item from the equipment window to the ground, the item remains transparent and falls to the ground. If you try to move it from the equipment to the bag it won't let you move it either. It only allows you to replace it with another object of the same type.

Regards

**Comment by frangaliano** [comment] 2023-12-09 15:16
Hi Jev,

If you want get for example your weapon from CharacterDialog interface and drop it to ground, appear this error.

For other hand, if you want drop one item from bag to ground, the item drop without any error.

**Comment by frangaliano** [comment] 2023-12-12 14:07
Any new about it?

**Comment by CookieLOM** [comment] 2024-12-10 14:41
> I don't think you're meant to be able to drop anything directly from equipped to floor.

As Jev said this is by design so that equipment cannot be dropped directly from the body/equipped state. Items need to go to the bag/inventory first then can be dropped from here.

**Comment by Lilcooldoode** [comment] 2024-12-10 17:37
Fixed in https://github.com/Suprcode/Crystal/commit/54f67fd63c311cfdc508e812a2c15f741e2b0059

**Closed by Lilcooldoode** 2024-12-10 17:37 UTC
